# Generated by Django 5.2.7 on 2025-11-06 20:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditSpread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_date",
                    models.DateField(help_text="The date that you open the spread"),
                ),
                (
                    "stock",
                    models.CharField(
                        help_text="The ticker of the underlying stock", max_length=10
                    ),
                ),
                (
                    "expiration",
                    models.DateField(help_text="The expiration date of the contracts"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BPS", "Bull Put Spread"),
                            ("BCS", "Bear Call Spread"),
                        ],
                        help_text="BPS for Bull Put Spread or BCS for Bear Call Spread",
                        max_length=3,
                    ),
                ),
                (
                    "long_strike",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="The strike price of the long leg (bought option)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "long_premium",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="The premium paid for the long leg",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "short_strike",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="The strike price of the short leg (sold option)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "short_premium",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="The premium received for the short leg",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "num_contracts",
                    models.IntegerField(
                        help_text="The number of spreads",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "open_fees",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.00"),
                        help_text="Total commissions and fees paid to open the spread",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "close_date",
                    models.DateField(
                        blank=True,
                        help_text="The date you close the position",
                        null=True,
                    ),
                ),
                (
                    "long_close_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="The premium received for closing the long leg",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "short_close_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="The premium paid to close the short leg",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "close_fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=Decimal("0.00"),
                        help_text="Commissions and fees paid to close the spread",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any notes or comments about the spread"
                    ),
                ),
                (
                    "current_long_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current price of the long leg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_short_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current price of the short leg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_spreads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-open_date", "stock"],
                "indexes": [
                    models.Index(fields=["stock"], name="CreditSprea_stock_c1e235_idx"),
                    models.Index(
                        fields=["open_date"], name="CreditSprea_open_da_b9bff0_idx"
                    ),
                    models.Index(
                        fields=["expiration"], name="CreditSprea_expirat_68753e_idx"
                    ),
                ],
            },
        ),
    ]
