# Generated by Django 5.2.7 on 2025-11-07 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreditSpread", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditspread",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="creditspread",
            index=models.Index(
                fields=["created_at"], name="CreditSprea_created_01c35a_idx"
            ),
        ),
    ]
