# Generated by Django 5.2.7 on 2025-10-28 19:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_date",
                    models.DateField(help_text="The date that you open the contract"),
                ),
                (
                    "stock",
                    models.CharField(
                        help_text="The ticker of the contract's underlying position",
                        max_length=10,
                    ),
                ),
                (
                    "set_number",
                    models.IntegerField(
                        default=1,
                        help_text="Track different tranches or sets of trades for the same underlying position",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "expiration",
                    models.DateField(help_text="The expiration date of the contract"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("P", "Put"), ("C", "Call")],
                        help_text="P for Put or C for Call",
                        max_length=1,
                    ),
                ),
                (
                    "num_contracts",
                    models.IntegerField(
                        help_text="The number of contracts",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "strike",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The strike price for the contract",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of premium received for selling your call or put",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "open_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commissions and fees paid to open a trade (total for all contracts)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "close_date",
                    models.DateField(
                        blank=True,
                        help_text="The date you close a position (or expiration date if held through expiration)",
                        null=True,
                    ),
                ),
                (
                    "assigned",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        help_text="Enter Yes if assigned shares or had shares called away, otherwise No",
                        max_length=3,
                    ),
                ),
                (
                    "premium_paid_to_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The amount paid to close the position (0 if held through expiration)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "close_fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commissions and fees paid to close a trade",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any notes or comments about the contract"
                    ),
                ),
                (
                    "current_option_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The mid price the option is currently trading for (from Yahoo Finance)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-open_date", "stock", "set_number"],
                "indexes": [
                    models.Index(
                        fields=["stock", "set_number"],
                        name="Dashboard_p_stock_e57988_idx",
                    ),
                    models.Index(
                        fields=["open_date"], name="Dashboard_p_open_da_031a24_idx"
                    ),
                    models.Index(
                        fields=["expiration"], name="Dashboard_p_expirat_bbd77f_idx"
                    ),
                ],
            },
        ),
    ]
