# Generated by Django 5.2.7 on 2025-10-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["-open_date", "stock"]},
        ),
        migrations.RemoveIndex(
            model_name="position",
            name="Dashboard_p_stock_e57988_idx",
        ),
        migrations.RemoveField(
            model_name="position",
            name="set_number",
        ),
        migrations.AddField(
            model_name="position",
            name="related_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to previous position in the wheel cycle (e.g., link a covered call to the put that got assigned)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_positions",
                to="Dashboard.position",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="wheel_cycle_name",
            field=models.CharField(
                blank=True,
                help_text="Optional name for this wheel cycle (e.g., 'AAPL Jan 2025', 'TSLA Wheel #1')",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["stock"], name="Dashboard_p_stock_fa6ce4_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["wheel_cycle_name"], name="Dashboard_p_wheel_c_b6572a_idx"
            ),
        ),
    ]
