# Generated by Django 5.2.7 on 2025-10-28 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0002_alter_position_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="rolled_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the position this was rolled to (if you rolled this position forward)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rolled_from",
                to="Dashboard.position",
            ),
        ),
    ]
