# Generated by Django 5.2.7 on 2025-10-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0003_position_rolled_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="rolled_to",
        ),
    ]
