# Generated by Django 5.2.7 on 2025-10-28 21:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0004_remove_rolled_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="close_fees",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("0.00"),
                help_text="Commissions and fees paid to close a trade",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="open_fees",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.00"),
                help_text="Commissions and fees paid to open a trade (total for all contracts)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="premium",
            field=models.DecimalField(
                decimal_places=3,
                help_text="The amount of premium received for selling your call or put",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="premium_paid_to_close",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="The amount paid to close the position (0 if held through expiration)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="strike",
            field=models.DecimalField(
                decimal_places=3,
                help_text="The strike price for the contract",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
