# Generated by Django 5.2.7 on 2025-10-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0005_update_decimal_precision"),
    ]

    operations = []
